name: JozeHladnik/jupyter-analyse
channels:
  - conda-forge
dependencies:
  - numpy
  - voila
  - matplotlib
  - pandas
  - seaborn
  - openpyxl
  #- bqplot
  #- folium
  #- bokeh
 # - dask
  #- psutil
